### ISSUE TITLE
ES 정렬 / 페이징 관련 논의

### ISSUE THREAD

**Issue by ReasonH** [deevly/memento-v2#8]
시나리오 - 클라이언트에서 인피니티 스크롤의 첫 번째 목록 조회

1. 1\~10 조회, search_after 11, 그러나 filter로 인해 결과는 1~5까지만 들어감
2. 11\~20 조회, search_after 21, 결과는 1\~5 + 11\~15로 클라이언트 전달
3. 이러면 클라이언트에서 다음 페이지 조회할 때 search_after는 어떻게 해야하는지?

[참조](https://opster.com/guides/elasticsearch/how-tos/elasticsearch-pagination-techniques/)
- search_after, pagination, indexing 등등 파악

**Comment by seongpyoHong** [comment]
페이징 및 정렬 : ES에 위임 - [search_after](https://wedul.site/541) 사용

**Comment by seongpyoHong** [comment]
논의 결과
- 일단은 기본 조회만 제공
  - 기본 조회란? resolved & solution URL을 제외한 검색

구현할 기능
- 전체 url 목록
- keyword 목록
- keyword 별 url 목록
- keyword 검색
